baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "muses"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[languages]
  [languages.en]
    title = "Muses"
    subtitle = "Digital Musical Instruments"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Muses"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "contributors"
        name = "contributors"
        url = "/contributors"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "projects"
        url = "/projects"
      [[languages.en.menu.main]]
        identifier = "github-repo"
        name = "the code"
        url = "https://github.com/muses-dmi"
      